import Navbar from './components/NavBar'
import Player from './components/Player'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-darkblue-300 ${inter.className}`}>
        <Navbar/>
        {children}
        <Player/>
      </body>
    </html>
  )
}
